// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// null

package unusedArchive.webservices.client;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.client.ServiceExceptionImpl;
import com.sun.xml.rpc.util.exception.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.client.HandlerChainImpl;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.rpc.handler.HandlerChain;
import javax.xml.rpc.handler.HandlerInfo;
import javax.xml.namespace.QName;

public class GMT_WebService_Impl extends com.sun.xml.rpc.client.BasicService implements GMT_WebService {
    private static final QName serviceName = new QName("http://gravity.usc.edu/gmt/ws/GMT_WS", "GMT_WebService");
    private static final QName ns1_GMT_WebServiceAPIPort_QNAME = new QName("http://gravity.usc.edu/gmt/ws/GMT_WS", "GMT_WebServiceAPIPort");
    private static final Class GMT_WebServiceAPI_PortClass = unusedArchive.webservices.client.GMT_WebServiceAPI.class;

    public GMT_WebService_Impl() {
        super(serviceName, new QName[] {
                        ns1_GMT_WebServiceAPIPort_QNAME
                    },
            new unusedArchive.webservices.client.GMT_WebService_SerializerRegistry().getRegistry());

    }

    public java.rmi.Remote getPort(QName portName, Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_GMT_WebServiceAPIPort_QNAME) &&
                serviceDefInterface.equals(GMT_WebServiceAPI_PortClass)) {
                return getGMT_WebServiceAPIPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }

    public java.rmi.Remote getPort(Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(GMT_WebServiceAPI_PortClass)) {
                return getGMT_WebServiceAPIPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }

    public unusedArchive.webservices.client.GMT_WebServiceAPI getGMT_WebServiceAPIPort() {
        String[] roles = new String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_GMT_WebServiceAPIPort_QNAME));
        handlerChain.setRoles(roles);
        unusedArchive.webservices.client.GMT_WebServiceAPI_Stub stub = new unusedArchive.webservices.client.GMT_WebServiceAPI_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
