// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build EA-R39)

package unusedArchive.webservices.client;

import javax.xml.rpc.*;

public interface GMT_WebService extends javax.xml.rpc.Service {
    public unusedArchive.webservices.client.GMT_WebServiceAPI getGMT_WebServiceAPIPort();
}
