package org.scec.mapping.gmtWrapper.gui;

import java.awt.*;
import java.awt.event.*;
import java.applet.*;
import javax.swing.*;
import javax.swing.border.*;

import org.scec.util.ImageUtils;

/**
 * <p>Title: GMT_MapGeneratorApplet</p>
 * <p>Description: this class displays the GMT Map generated by the class
 * GMT_MapGenerator as the imagei(.jpg) Label in the window</p>
 * @author :Nitin Gupta and Vipin Gupta
 * @version 1.0
 */

public class GMT_MapGeneratorApplet extends Applet {


  private static final String C="GMT_MapGeneratorApplet";

  private static final boolean D= false;


  private boolean isStandalone = false;
  private BorderLayout borderLayout1 = new BorderLayout();
  private JPanel mainPanel = new JPanel();
  private JSplitPane mainSplitPane = new JSplitPane();
  private JPanel buttonPanel = new JPanel();
  private JSplitPane plotSplitPane = new JSplitPane();
  private JPanel parameterPanel = new JPanel();

  // default insets
  Insets defaultInsets = new Insets( 4, 4, 4, 4 );
  String mapFileName = null;

  //variables that determine the window size
  protected final static int W = 850;
  protected final static int H = 700;
  private Border border1;
  private JButton addButton = new JButton();

  private GMT_GuiBean gmtGuiBean=null;
  private GridBagLayout gridBagLayout1 = new GridBagLayout();
  private GridBagLayout gridBagLayout3 = new GridBagLayout();
  private GridBagLayout gridBagLayout2 = new GridBagLayout();
  private JScrollPane mapScrollPane = new JScrollPane();
  private JPanel mapPanel = new JPanel();
  private JLabel gmtMapLabel = new JLabel();
  private Border border2;
  private GridBagLayout gridBagLayout4 = new GridBagLayout();

  //Get a parameter value
  public String getParameter(String key, String def) {
    return isStandalone ? System.getProperty(key, def) :
      (getParameter(key) != null ? getParameter(key) : def);
  }

  //Construct the applet
  public GMT_MapGeneratorApplet() {
  }
  //Initialize the applet
  public void init() {
    try {
      jbInit();
      gmtGuiBean =new GMT_GuiBean();
      //panel to display the GMT adjustable parameters
      parameterPanel.add(gmtGuiBean.getGMT_ParamEditor(),new GridBagConstraints( 0, 0, 1, 1, 1.0, 1.0,
                    GridBagConstraints.CENTER,
                    GridBagConstraints.BOTH, defaultInsets, 0, 0 ));
    }
    catch(Exception e) {
      e.printStackTrace();
    }
  }
  //Component initialization
  private void jbInit() throws Exception {
    border1 = BorderFactory.createEtchedBorder(new Color(248, 254, 255),new Color(121, 124, 136));
    border2 = BorderFactory.createLineBorder(SystemColor.controlText,1);
    this.setSize(new Dimension(802, 686));
    this.setLayout(borderLayout1);
    mainPanel.setLayout(gridBagLayout3);
    mainSplitPane.setOrientation(JSplitPane.VERTICAL_SPLIT);
    buttonPanel.setLayout(gridBagLayout2);
    parameterPanel.setLayout(gridBagLayout1);
    addButton.setText("Add");
    addButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(ActionEvent e) {
        addButton_actionPerformed(e);
      }
    });
    gmtMapLabel.setBorder(border2);
    gmtMapLabel.setMaximumSize(new Dimension(0, 800));
    gmtMapLabel.setMinimumSize(new Dimension(0, 600));
    gmtMapLabel.setPreferredSize(new Dimension(0, 600));
    mapPanel.setLayout(gridBagLayout4);
    mapPanel.setMinimumSize(new Dimension(0, 800));
    mapPanel.setPreferredSize(new Dimension(0, 800));
    this.add(mainPanel, BorderLayout.CENTER);
    mainPanel.add(mainSplitPane,  new GridBagConstraints(0, 0, 1, 1, 1.0, 1.0
            ,GridBagConstraints.CENTER, GridBagConstraints.BOTH, new Insets(4, 4, 6, 6), 0, 527));
    mainSplitPane.add(buttonPanel, JSplitPane.RIGHT);
    buttonPanel.add(addButton,  new GridBagConstraints(0, 0, 1, 1, 0.0, 0.0
            ,GridBagConstraints.CENTER, GridBagConstraints.NONE, new Insets(3, 17, 6, 659), 22, 9));
    mainSplitPane.add(plotSplitPane, JSplitPane.LEFT);
    plotSplitPane.add(parameterPanel, JSplitPane.RIGHT);
    plotSplitPane.add(mapScrollPane, JSplitPane.LEFT);
    mapScrollPane.getViewport().add(mapPanel, null);
    mapPanel.add(gmtMapLabel,  new GridBagConstraints(0, 0, 1, 1, 0.0, 0.0
            ,GridBagConstraints.WEST, GridBagConstraints.NONE, new Insets(0, 0, 0, 0), 557, 200));
    mainSplitPane.setDividerLocation(620);
    plotSplitPane.setDividerLocation(588);
  }


  //Start the applet
  public void start() {
  }
  //Stop the applet
  public void stop() {
  }
  //Destroy the applet
  public void destroy() {
  }
  //Get Applet information
  public String getAppletInfo() {
    return "MAPS using the GMT";
  }
  //Get parameter info
  public String[][] getParameterInfo() {
    return null;
  }
  //Main method
  public static void main(String[] args) {
    GMT_MapGeneratorApplet applet = new GMT_MapGeneratorApplet();
    applet.isStandalone = true;
    JFrame frame = new JFrame();
    //EXIT_ON_CLOSE == 3
    frame.setDefaultCloseOperation(3);
    frame.setTitle("Maps");
    frame.getContentPane().add(applet, BorderLayout.CENTER);
    applet.init();
    applet.start();
    frame.setSize(W,H);
    Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
    frame.setLocation((d.width - frame.getSize().width) / 2, (d.height - frame.getSize().height) / 2);
    frame.setVisible(true);
  }

  //static initializer for setting look & feel
  static {
    try {
      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
      //UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
    }
    catch(Exception e) {
    }
  }

  void addButton_actionPerformed(ActionEvent e) {
    addButton();
  }


  /**
   * this method calls the generate Map function to generate the jpg image file of the
   * Map
   */
  void addButton() {
    String imgName=gmtGuiBean.generateMap()+".jpg";

    //mapPanel.removeAll();
    gmtMapLabel.setIcon(new ImageIcon(imgName));
    //Graphics g=gmtMapLabel.getGraphics();
    //if (g!=null) gmtMapLabel.paintComponents(g);
    //mapPanel.add(gmtMapLabel,   new GridBagConstraints(0, 0, 1, 1, 0.0, 0.0
      //      ,GridBagConstraints.CENTER, GridBagConstraints.BOTH, new Insets(0, 2, 1, 0), 0, 0));
    //gmtMapLabel.paintImmediately(gmtMapLabel.getBounds());
    //gmtMapLabel.validate();
    //gmtMapLabel.repaint(100);
    //mapPanel.setMapFileName(imgName);
    //mapPanel.validate();
    //mapPanel.repaint();
  }
}




/*class ImagePanel extends JPanel {
  // name of the image file to show
  private String mapFileName = null;


  /**
   * override the paint method to show the image
   * @param g

  public void paintComponent(java.awt.Graphics g) {
    //System.out.println("Paint called with mapFileName:"+mapFileName);
    //super.paint(g);
    if(mapFileName!=null) g.drawImage(Toolkit.getDefaultToolkit().getImage(mapFileName),0,0,this);

   // super.paint(g);
  }


  /**
   * set the name of new image file to show
   * @param newFileName

  public void setMapFileName(String newFileName) {
    mapFileName = newFileName;
  }


}*/

